In [1]:
import os
import scipy.io.wavfile

labeled_recording_files = os.listdir('free-spoken-digit\\dev')

wave = scipy.io.wavfile.read('free-spoken-digit\\dev\\1201_5.wav')

dataset_labeled= {}
id_label_dictionary = {}

for string in labeled_recording_files:
    wav = scipy.io.wavfile.read('free-spoken-digit\\dev\\'+string)
    #read a single file and for each of them extract info about id and label
    wav_id = string.split('_')[0]
    wav_label = string.split('_')[1].split('.')[0]
    #then insert it in the dataset
    dataset_labeled[int(wav_id)] = wav
    id_label_dictionary[int(wav_id)] = int(wav_label)
    

In [44]:
print(wave)

(8000, array([-22, -15,  28, ...,  21,  61,  25], dtype=int16))


In [49]:
print(dataset_labeled[1201])

(8000, array([-22, -15,  28, ...,  21,  61,  25], dtype=int16))


Now i verify if the array length is the same for each wav file

In [2]:
for v, k in zip(dataset_labeled.values(), dataset_labeled.keys()):
    print('Data: ', len(v[1]), '  fileId: ', k)

Data:  3124   fileId:  0
Data:  3103   fileId:  1000
Data:  2415   fileId:  1001
Data:  4751   fileId:  1002
Data:  3888   fileId:  1003
Data:  3945   fileId:  1004
Data:  2621   fileId:  1005
Data:  1781   fileId:  1006
Data:  3204   fileId:  1007
Data:  3601   fileId:  1008
Data:  2149   fileId:  1009
Data:  3114   fileId:  100
Data:  5563   fileId:  1010
Data:  3131   fileId:  1011
Data:  3401   fileId:  1012
Data:  2414   fileId:  1013
Data:  2797   fileId:  1014
Data:  3096   fileId:  1015
Data:  3005   fileId:  1016
Data:  1749   fileId:  1017
Data:  3201   fileId:  1018
Data:  4196   fileId:  1019
Data:  2377   fileId:  101
Data:  3165   fileId:  1020
Data:  3303   fileId:  1021
Data:  3179   fileId:  1022
Data:  2863   fileId:  1023
Data:  4001   fileId:  1024
Data:  2223   fileId:  1025
Data:  1560   fileId:  1026
Data:  1294   fileId:  1027
Data:  2324   fileId:  1028
Data:  3865   fileId:  1029
Data:  3722   fileId:  102
Data:  3519   fileId:  1030
Data:  4062   fileId:  103

Data:  4423   fileId:  126
Data:  2384   fileId:  1270
Data:  4970   fileId:  1271
Data:  4496   fileId:  1272
Data:  2333   fileId:  1273
Data:  2538   fileId:  1274
Data:  3100   fileId:  1275
Data:  3889   fileId:  1276
Data:  4889   fileId:  1277
Data:  3591   fileId:  1278
Data:  4303   fileId:  1279
Data:  4048   fileId:  127
Data:  3397   fileId:  1280
Data:  3642   fileId:  1281
Data:  3236   fileId:  1282
Data:  3307   fileId:  1283
Data:  3031   fileId:  1284
Data:  2983   fileId:  1285
Data:  2279   fileId:  1286
Data:  2257   fileId:  1287
Data:  2518   fileId:  1288
Data:  2192   fileId:  1289
Data:  1914   fileId:  128
Data:  2619   fileId:  1290
Data:  3839   fileId:  1291
Data:  3005   fileId:  1292
Data:  2531   fileId:  1293
Data:  3892   fileId:  1294
Data:  2628   fileId:  1295
Data:  4605   fileId:  1296
Data:  2348   fileId:  1297
Data:  2891   fileId:  1298
Data:  2795   fileId:  1299
Data:  4343   fileId:  129
Data:  3274   fileId:  12
Data:  2036   fileId:  130

Data:  1850   fileId:  355
Data:  2821   fileId:  356
Data:  3349   fileId:  357
Data:  3902   fileId:  358
Data:  2407   fileId:  359
Data:  2532   fileId:  35
Data:  2653   fileId:  360
Data:  3410   fileId:  361
Data:  2259   fileId:  362
Data:  4074   fileId:  363
Data:  3472   fileId:  364
Data:  2033   fileId:  365
Data:  2199   fileId:  366
Data:  2554   fileId:  367
Data:  2396   fileId:  368
Data:  3482   fileId:  369
Data:  3539   fileId:  36
Data:  3092   fileId:  370
Data:  3602   fileId:  371
Data:  1713   fileId:  372
Data:  1640   fileId:  373
Data:  4495   fileId:  374
Data:  2823   fileId:  375
Data:  3569   fileId:  376
Data:  5510   fileId:  377
Data:  1579   fileId:  378
Data:  4606   fileId:  379
Data:  2320   fileId:  37
Data:  4014   fileId:  380
Data:  2828   fileId:  381
Data:  2910   fileId:  382
Data:  2518   fileId:  383
Data:  4260   fileId:  384
Data:  4629   fileId:  385
Data:  5167   fileId:  386
Data:  2039   fileId:  387
Data:  2624   fileId:  388
Data

Data:  2702   fileId:  760
Data:  3583   fileId:  761
Data:  3431   fileId:  762
Data:  2112   fileId:  763
Data:  2397   fileId:  764
Data:  2898   fileId:  765
Data:  2629   fileId:  766
Data:  4571   fileId:  767
Data:  3664   fileId:  768
Data:  3536   fileId:  769
Data:  5266   fileId:  76
Data:  2318   fileId:  770
Data:  1737   fileId:  771
Data:  3232   fileId:  772
Data:  1801   fileId:  773
Data:  3303   fileId:  774
Data:  2815   fileId:  775
Data:  2064   fileId:  776
Data:  2829   fileId:  777
Data:  3343   fileId:  778
Data:  3275   fileId:  779
Data:  3668   fileId:  77
Data:  3688   fileId:  780
Data:  2062   fileId:  781
Data:  4112   fileId:  782
Data:  4108   fileId:  783
Data:  3733   fileId:  784
Data:  3678   fileId:  785
Data:  3431   fileId:  786
Data:  1854   fileId:  787
Data:  4351   fileId:  788
Data:  3380   fileId:  789
Data:  2343   fileId:  78
Data:  2490   fileId:  790
Data:  3137   fileId:  791
Data:  2426   fileId:  792
Data:  2566   fileId:  793
Data

There are several different lengths which means that the each file has a different amount of data...
BUT isn't true that more data correspond to more information, instead it could be some noise, or the audio was recorder at higher volume.
Listening the samples i heard that a sample with a data array length < 2000 is tipically not really relevant because the number pronunciation is truncated before finishing it (E.g. instead to say "six" the speaker has recorded only "si"), in the other hand a sample with length > 5500 is often (maybe always) either with noise or the speaker was screaming.


In [44]:
import matplotlib.pyplot as plt

fig, ax = plt.subplots(5, 2, figsize=[18,30])

ax[0,0].set_title('File 1000, "0"')
ax[0,1].set_title('File 20, "1"')
ax[1,0].set_title('File 101, "2"')
ax[1,1].set_title('File 176, "3"')
ax[2,0].set_title('File 0, "4"')
ax[2,1].set_title('File 1201, "5"')
ax[3,0].set_title('File 396, "6"')
ax[3,1].set_title('File 597, "7"')
ax[4,0].set_title('File 639, "8"')
ax[4,1].set_title('File 911, "9"')

ax[0,0].plot(dataset_labeled[1000][1])
ax[0,1].plot(dataset_labeled[20][1])
ax[1,0].plot(dataset_labeled[101][1])
ax[1,1].plot(dataset_labeled[176][1])
ax[2,0].plot(dataset_labeled[0][1])
ax[2,1].plot(dataset_labeled[1201][1])
ax[3,0].plot(dataset_labeled[396][1])
ax[3,1].plot(dataset_labeled[597][1])
ax[4,0].plot(dataset_labeled[639][1])
ax[4,1].plot(dataset_labeled[911][1])



In [26]:
id_label_dictionary[1000]

0

In [45]:
from numpy.fft import *
from numpy import log10, sqrt, array, zeros, ones, multiply

fig, ax = plt.subplots(5, 2, figsize=[18,30])

ax[0,0].set_title('File 1000, "0"')
ax[0,1].set_title('File 20, "1"')
ax[1,0].set_title('File 101, "2"')
ax[1,1].set_title('File 176, "3"')
ax[2,0].set_title('File 0, "4"')
ax[2,1].set_title('File 1201, "5"')
ax[3,0].set_title('File 396, "6"')
ax[3,1].set_title('File 597, "7"')
ax[4,0].set_title('File 639, "8"')
ax[4,1].set_title('File 911, "9"')

ax[0,0].plot(fft(dataset_labeled[1000][1]))
ax[0,1].plot(fft(dataset_labeled[20][1]))
ax[1,0].plot(fft(dataset_labeled[101][1]))
ax[1,1].plot(fft(dataset_labeled[176][1]))
ax[2,0].plot(fft(dataset_labeled[0][1]))
ax[2,1].plot(fft(dataset_labeled[1201][1]))
ax[3,0].plot(fft(dataset_labeled[396][1]))
ax[3,1].plot(fft(dataset_labeled[597][1]))
ax[4,0].plot(fft(dataset_labeled[639][1]))
ax[4,1].plot(fft(dataset_labeled[911][1]))


c:\users\ruben\appdata\local\programs\python\python37-32\lib\site-packages\numpy\core\_asarray.py:85: ComplexWarning: Casting complex values to real discards the imaginary part
  return array(a, dtype, copy=False, order=order)


In [32]:
import numpy as np
label_array = np.array(list(id_label_dictionary.values()))
np.unique(label_array, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([150, 150, 150, 150, 150, 150, 150, 150, 150, 150]))

As we can see our dataset is perfectly balanced

In [46]:
#In the following steps i will remove noisy record according with the previous considerations
clean_labeled_dataset = {}
clean_id_label_dictionary = {}

for code, wav in zip(dataset_labeled.keys(), dataset_labeled.values()):
    length = len(wav[1])
    if length < 5500 and length > 2000:
        #the wav files is good for classification, otherwise it isn't
        clean_labeled_dataset[code] = wav
        clean_id_label_dictionary[code] = id_label_dictionary[code]

In [47]:
#actually i recall again the numpy's unique function to see if the cleaned db is already balanced
label_array = np.array(list(clean_id_label_dictionary.values()))
np.unique(label_array, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([146, 134, 129, 121, 146, 147,  91, 146, 143, 146]))

Our dataset is not balanced anymore, probably we have a critical point on a label '6'


To build a classification model, i will split my cleaned data in a training and test set, but first of all i need to have all equal length array that rapresent my wav files

In [49]:
fft_dictionary = {}

for code, wav in zip(clean_labeled_dataset.keys(), clean_labeled_dataset.values()):
    fft_dictionary[code] = fft(wav[1])   


In [74]:
fft_dictionary[101].shape

(2377,)

In [273]:
#this functions is aimed to calculate for each wav files, a vector which contains a number of means according 
#with the nPartitions parameter. In practise it splits the time dimension in 'nPartitions' sets which have all the same length
#Finally the function returns the result in a dictionary where a key is the original id taken from the original dataset

def compute_vector_using_mean(clean_labeled_dataset, nPartitions):
    
    X = {}
    
    for k,v in zip(clean_labeled_dataset.keys(), clean_labeled_dataset.values()):
        length = len(v[1])
        parts = []
        for i in range(1,nPartitions):
            parts.append(int(length / nPartitions * i))
            
        wav = v[1]
        mean_array = [np.mean(wav[:parts[0]])]
        for j in range(1,len(parts)-1):
            mean_array.append(np.mean(wav[parts[j]:parts[j+1]]))
            
        X[k] = np.array(mean_array)    
            
        
    return X    

X = compute_vector_using_mean(clean_labeled_dataset, 16)

In [274]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(list(X.values()), list(clean_id_label_dictionary.values()), test_size = 0.20)

In [275]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(max_depth=24, min_impurity_decrease= 0.002)
clf.fit(X_train, y_train)
y_test_pred = clf.predict(X_test)

In [276]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, confusion_matrix

# Compute accuracy
acc = accuracy_score(y_test, y_test_pred)
print(f"Accuracy = {acc:.2f}")

Accuracy = 0.26


I can see how ACCURANCY changes by increasing number of partitions

In [293]:
def acc_vector(boundary):
    accScores = []
    for i in range(2,boundary):
        X = compute_vector_using_mean(clean_labeled_dataset, i)
        X_train, X_test, y_train, y_test = train_test_split(list(X.values()), list(clean_id_label_dictionary.values()), test_size = 0.20)
        clf = DecisionTreeClassifier(max_depth=24, min_impurity_decrease= 0.002)
        clf.fit(X_train, y_train)
        y_test_pred = clf.predict(X_test)
        acc = accuracy_score(y_test, y_test_pred)
        accScores.append(acc)
        
    return accScores   

accurancy_vector = acc_vector(20)

In [292]:
%matplotlib notebook
plt.plot(accurancy_vector)

<IPython.core.display.Javascript object>

Taking into account that the function start from 2 partitions, best best accurancy vector occur when the partitions are 16

In [125]:
# Precision, recall, f1, support: for each class
p, r, f1, support = precision_recall_fscore_support(y_test, y_test_pred)

for c in range(p.shape[0]):
    print(f"\nClass {c}:")
    print(f"number of items: {support[c]}")
    print(f"p = {p[c]:.2f}")
    print(f"r = {r[c]:.2f}")
    print(f"f1 = {f1[c]:.2f}")

# Macro average f1
macro_f1 = f1.mean()
    
# This score is important when you have class imbalancing
print(f"\nF1, macro-average: {macro_f1:2f}")


Class 0:
number of items: 28
p = 0.25
r = 0.29
f1 = 0.27

Class 1:
number of items: 26
p = 0.27
r = 0.23
f1 = 0.25

Class 2:
number of items: 24
p = 0.24
r = 0.29
f1 = 0.26

Class 3:
number of items: 24
p = 0.13
r = 0.08
f1 = 0.10

Class 4:
number of items: 31
p = 0.32
r = 0.29
f1 = 0.31

Class 5:
number of items: 22
p = 0.18
r = 0.18
f1 = 0.18

Class 6:
number of items: 22
p = 0.40
r = 0.55
f1 = 0.46

Class 7:
number of items: 35
p = 0.14
r = 0.09
f1 = 0.11

Class 8:
number of items: 24
p = 0.35
r = 0.46
f1 = 0.40

Class 9:
number of items: 34
p = 0.30
r = 0.35
f1 = 0.32

F1, macro-average: 0.266329
